site_name: Cisco IOS Commands - CCNA
site_url: https://ccna-commands.example
theme:
  name: material
  font:
    code: Red Hat Mono
  logo: assets/Router-Firewall.svg
  favicon: assets/Router-Firewall.svg
  features:
    - navigation.footer
    - navigation.path
    - navigation.indexes
    - toc.follow
    - navigation.expand
    - navigation.sections
    - content.code.copy
    - content.code.select
    - content.code.annotate
  palette:
    scheme: slate
    primary: green
nav: 
  - Home: index.md
  - Basics and Navigation:
      - "IOS CLI Navigation": navigation.md
      - "Basic Device Configuration": basic-device-config.md
      - "Interface Configuration": interface-config.md
  - Security Hardening: security-hardening.md
  - VLANs and Trunking: vlans.md
  - Spanning Tree Protocol: stp.md
  - EtherChannel: etherchannel.md
  - IPv6: ipv6.md
  - Static Routing: static-routing.md
  - Dynamic Routing - OSPF: dynamic-routing.md
  - Access Control Lists: acl.md
  - NAT: nat.md
  - DHCP: dhcp.md
  - First Hop Redundancy Protocols: fhrp.md
  - Tunnels and VPNs: vpn-tunnels.md
  - Troubleshooting: troubleshooting.md
  - Miscellaneous: misc.md

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.highlight

extra:
  social:
    - icon: simple/github
      link: https://github.com/Edm0ndDantes